spring.application.name=todo

# ===================== SQL Server =====================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TodoDb;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Sam@12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# ===================== Swagger / OpenAPI =====================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs